# Generated by Django 5.2.7 on 2025-10-12 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Supplier's company name", max_length=200)),
                ('contact_person', models.CharField(help_text='Primary contact person', max_length=200)),
                ('email', models.EmailField(help_text="Supplier's email address", max_length=254)),
                ('phone_number', models.CharField(help_text="Supplier's phone number", max_length=20)),
                ('address', models.TextField(help_text="Supplier's address")),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Supplier rating (0.0 to 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether supplier is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
