# Generated by Django 5.2.7 on 2025-10-12 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(help_text='Type of product ordered', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of products ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=12)),
                ('delivery_date', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-preparation', 'In Preparation'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current order status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional order notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier assigned to fulfill the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('system', 'System'), ('outgoing', 'Outgoing'), ('incoming', 'Incoming')], help_text='Type of message', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('sender', models.CharField(blank=True, help_text='Message sender (if not system)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Message',
                'verbose_name_plural': 'Order Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
